# Generated by Django 5.2.7 on 2025-11-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(default='Pizzas', max_length=30)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.TextField(default='1000 cup')),
                ('foto', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
