# Generated by Django 5.2.7 on 2025-11-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_alter_pizzas_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzas',
            name='foto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
