# Generated by Django 5.2.7 on 2025-11-17 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(default='Juan', max_length=20)),
                ('nombre_oferta', models.CharField(default='Pizza de Queso', max_length=20)),
                ('numero_oferta', models.IntegerField(default=1)),
                ('comentario', models.TextField()),
                ('resumen', models.CharField(default='Exquisito', max_length=23)),
                ('gradoSatisfaccion', models.TextField(default='Bien')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
