# Generated by Django 5.2.7 on 2025-11-11 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_comentarios_numero_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
