# Generated by Django 5.2.7 on 2025-11-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0005_alter_comentarios_gradosatisfaccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='resumen',
            field=models.CharField(default='Exquisito', max_length=23),
        ),
    ]
