# Generated by Django 5.2.5 on 2025-11-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0007_comentarios_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='calificacion',
        ),
    ]
