# Generated by Django 5.2.7 on 2025-11-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzas',
            name='seccion',
            field=models.CharField(choices=[('PIZZAS', 'Pizzas'), ('SPAGHETTIS', 'Spaghettis'), ('ENTRANTES', 'Entrantes')], default='PIZZAS', max_length=30),
        ),
    ]
