# Generated by Django 5.2.7 on 2025-11-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=20)),
                ('comentario', models.TextField()),
                ('resumen', models.CharField(max_length=20)),
                ('gradoSatisfaccion', models.TextField()),
            ],
        ),
    ]
