# Generated by Django 5.2.7 on 2025-11-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='nombre_oferta',
            field=models.CharField(default='Pizza de Queso', max_length=20),
        ),
    ]
