# Generated by Django 5.2.7 on 2025-11-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentarios_nombre_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='numero_oferta',
            field=models.IntegerField(default=1),
        ),
    ]
