# Generated by Django 5.2.7 on 2025-11-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_comentarios_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='gradoSatisfaccion',
            field=models.TextField(default='Bien'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='nombre_persona',
            field=models.CharField(default='Juan', max_length=20),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='resumen',
            field=models.CharField(default='Exquisito', max_length=20),
        ),
    ]
