# Generated by Django 5.2.5 on 2025-11-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0006_alter_comentarios_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='calificacion',
            field=models.CharField(blank=True, default='Sin calificar', max_length=9),
        ),
    ]
